# Generated by Django 4.2.5 on 2023-10-05 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_folder_user_delete_file_delete_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='conf_password',
        ),
    ]
